### ISSUE TITLE
Tasking Manager % is wrong

### ISSUE THREAD

**Issue by dalekunce** [MissingMaps/partners#26]
The % complete from the TM is way way off.

<img width="850" alt="screen shot 2016-06-24 at 10 33 51 am" src="https://cloud.githubusercontent.com/assets/1913857/16340631/33fd0632-39f7-11e6-9733-be5707cfc665.png">

**Comment by dalekunce** [comment]
@DylanMoriarty @smit1678 did you see this issue? Thoughts?

**Comment by DylanMoriarty** [comment]
@dalekunce This seems to be an issue with the HOT Tasking Manager API. 

Looking at http://www.missingmaps.org/partners/all/ 's task, #1544 on the face it has the current numbers [you can see it here](http://tasks.hotosm.org/project/1544). However, if you [grab the json](http://tasks.hotosm.org/project/1544.json), which is where we get our data from, the numbers under both validated & done don't match the face.

**Comment by dalekunce** [comment]
thanks filed an issue on the tasking manager repo.

https://github.com/hotosm/osm-tasking-manager2/issues/833

**Comment by DylanMoriarty** [comment]
Tasking manager determines completeness by just summing 'done' & 'validation'. Goofy, but functional. Change has been made.
